### ISSUE TITLE
Service 503-ing for hasOwnProperty

### ISSUE THREAD

**Issue by geoffharcourt** [JakeChampion/polyfill-service#2652]
## What

It appears that while the basic polyfill returns successfully, polyfills containing `hasOwnProperty` are 503-ing.

## Details

Visit:
https://polyfill.io/v3/polyfill.min.js?features=hasOwnProperty

**Comment by geoffharcourt** [comment]
I did some testing to see what features cause this issue, and it appears that `hasOwnProperty` causes the failure. This URL works without it, and polyfilling `hasOwnProperty` alone causes a 503.

**Comment by geoffharcourt** [comment]
A note: I got this in my API URL because `create-polyfill-url-service` now provides it. Not sure if there's a version mismatch going on.

**Comment by JakeChampion** [comment]
Howdy, no version mismatch but a real bug in polyfill-library which I am now fixing 👍

**Comment by geoffharcourt** [comment]
Hi @JakeChampion can you bump the service now that your fix is in? Thank you so much for resolving the library issue!

**Comment by JakeChampion** [comment]
Howdy - we are currently fixing a regression in the polyfill-library which is blocking the release to polyfill.io - once that is fixed the release to polyfill.io will happen 👍

**Comment by geoffharcourt** [comment]
Thanks @JakeChampion!
