### ISSUE TITLE
Safari on iOS 14 is being detected as iOS 11

### ISSUE THREAD

**Issue by dapenguin** [JakeChampion/polyfill-service#2653]
## What

We have noticed that when using Safari on an iPhone 12 on iOS 14, `fetch` (among other things) is being polyfilled when it doesn't need to. This has caused some unexpected issues with some DataDog client-side JavaScript we are using.

### To reproduce

1. Using Chrome's dev tools, set the User Agent String to: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1`
2. Go to the following polyfil.io URL: https://polyfill.io/v3/polyfill.min.js?features=es2017%2Ces2016%2Ces2015%2Cdefault%2CArray.prototype.contains%2CDOMTokenList.prototype.%40%40iterator%2CDocumentFragment%2CEventSource%2CFunction.name%2CIntersectionObserver%2CMutationObserver%2CNodeList.prototype.%40%40iterator%2CObject.freeze%2CPromise.prototype.finally%2CString.fromCodePoint%2CString.prototype.contains%2CUserTiming%2CWebAnimations%2Cfetch%2ClocalStorage%2CmatchMedia%2Cnavigator.sendBeacon%2Cperformance.now%2Cscreen.orientation%2CsetImmediate%2CResizeObserver%2CAbortController%2CIntl.PluralRules,Intl.PluralRules.~locale.en
3. Go to the Network Tab in Dev Tools.

This can also be reproduced simulating an iPhone 12 on iOS 14 using Simulator on a Mac or using BrowserStack.

### Expected result

- The response should not contain any code for polyfilling `fetch`
- The `detected-user-agent` response header should have a value like `Mobile Safari/WKWebView/14..`
- The `normalized-user-agent` response header should have a value like `ios_saf/14.0.3`

### Actual result

- The response contains code for polyfilling `fetch`
- The `detected-user-agent` response header has the value `Mobile Safari/WKWebView/11..`
- The `normalized-user-agent` response header has a value of `ios_saf/11.0.0`

The following screen grab shows the above result:
![](https://user-images.githubusercontent.com/6975428/144453228-d8e04f21-981e-4207-a18b-b077038ea9b3.png)

## Additional information

I believe the good work done in https://github.com/Financial-Times/useragent_parser/pull/101 should have fixed it, and when running the service locally it works as expected. Is it possible that there's a cache that needs clearing?

**Comment by christianhaller3000** [comment]
maybe related to https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/175

**Comment by JakeChampion** [comment]
Thanks all, we have a pull-request open to fix this now -> https://github.com/Financial-Times/polyfill-service/pull/2669

**Comment by dapenguin** [comment]
@JakeChampion Using the above steps, I still seem to be able to recreate this issue.

**Comment by JakeChampion** [comment]
Apologies, it has yet to be released to production - I will do that today

**Comment by dapenguin** [comment]
Thank you! I will learn to be more patient 😄

**Comment by JakeChampion** [comment]
If you wanted to see when the deployment finishes - you can view the deployment workflow https://github.com/Financial-Times/polyfill-service/actions/runs/1892925152/attempts/2

**Comment by JakeChampion** [comment]
The deployment has happened and we are beginning to mark the cached content as stale now in the cdn

**Comment by dapenguin** [comment]
Nice one! Can confirm that we are getting the expected response. Thanks for your work on this @JakeChampion
