### ISSUE TITLE
[question] Deploys to production are failing?

### ISSUE THREAD

**Issue by ghost** [JakeChampion/polyfill-service#2666]
I'm not sure if the deployments to prod are effective or not. Here we see some failures in the pipes:
https://github.com/Financial-Times/polyfill-service/actions/runs/1779486094

As a consequence, this fix does not seem to be deployed in production:
https://github.com/Financial-Times/useragent_parser/issues/100

As a prof of it, a request to production with a Mobile Safari 14 user-agent is still is detecting It wrongly (returning the `fetch` polyfill when It should not):
```
curl 'https://polyfill.io/v3/polyfill.js?features=fetch' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1'
 ```
 
But a [local build ](https://github.com/Financial-Times/polyfill-service/blob/master/.github/CONTRIBUTING.md#getting-started) of the current `master` seems to work fine for me:
 ```
curl 'http://localhost:8080/v3/polyfill.js?features=fetch' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1'
 ```
 
My conclusion is that `master` does contain the fix and works fine, but the production host does not contain the fix, so may be the deployments to prod are really failing.

Let me know if I can help somehow. Thanks so much!

**Comment by ghost** [comment]
hi @JakeChampion
Could you please confirm if deployments to prod are working as expected?

**Comment by JakeChampion** [comment]
Howdy, deployments are working, the issue you are seeing in our GitHub workflow is a script which runs after deployment and is failing - it is something we plan to look into but is not urgent as it does not block deployments and is more of a nice-to-have post-deployment feature.

**Comment by ghost** [comment]
@JakeChampion amazing! thanks a lot for the fast response :)

I walk you through the problem briefly.

Technically there is this dependency hierarchy from `polyfill-service#master`:
- `"@financial-times/polyfill-useragent-normaliser": "1.9.0"`
  - `"@financial-times/useragent_parser": "^1.6.0"`

That means the fix for the [iOS user-agent problem made on useragent_parser#v1.6.0](https://github.com/Financial-Times/useragent_parser/releases/tag/v1.6.0), _should_ be deployed on prod.

But unfortunately the behavior of prod doesn't seem to reflect that fix.
A local build, however, seems to work fine.

The first curl command that I posted initially demonstrates the detection in iOS is still failing.

Is there some way I can help to debug that problem? Thanks so much :pray:

**Comment by JakeChampion** [comment]
@carles-thn Thanks, I've got enough information in the issue description - I'll look into this now 👍

**Comment by JakeChampion** [comment]
@carles-thn it looks like we do have that version in the service, I'm doing some more debugging on this

**Comment by JakeChampion** [comment]
@carles-thn I have made a pull-request which should fix this -> https://github.com/Financial-Times/polyfill-service/pull/2669
