### ISSUE TITLE
Your Service Is Being Used By Organized Terror Organizations

### ISSUE THREAD

**Issue by alhion** [JakeChampion/polyfill-service#2668]
ISIS is using your service to hack my network.
 polyfill.io
    ----------------------------------------
    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.1.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.193.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.65.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.129.26

    polyfill.io
    ----------------------------------------
    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.1.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.193.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.65.26

    Record Name . . . . . : polyfill.io
    Record Type . . . . . : 1
    Time To Live  . . . . : 76065
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 151.101.129.26

**Comment by JakeChampion** [comment]
Hi @alhion - could you explain some more please? The text you've posted looks to be a DNS lookup of polyfill.io and shows the expected A record values that we use.
