### ISSUE TITLE
v4 availability at polyfill.io site?

### ISSUE THREAD

**Issue by coliff** [JakeChampion/polyfill-service#2687]
I currently use https://polyfill.io/v3/polyfill.min.js on a few sites. I saw that there have been several polyfill v4 releases.

Are the latest updates available as part of https://polyfill.io/v3/polyfill.min.js or will there be a https://polyfill.io/v4/polyfill.min.js ?

**Comment by JakeChampion** [comment]
Yes the latest version of the api endpoint is v3 and that has the latest updates 👍 the versioning you see on the git tags and the github releases is not the same as the versioning on the api endpoints

**Comment by coliff** [comment]
thanks for the quick reply and the awesome service. 🥇
