### ISSUE TITLE
cdn.polyfill.io/v1 not accessible again

### ISSUE THREAD

**Issue by msbannert** [JakeChampion/polyfill-service#2739]
Not sure if this is the right place for this bug report, but its the only one i found:
since Feb-21-2023, a https request to https://cdn.polyfill.io/v1/polyfill.min.js returns 404 on many locations of the world (but not all), so there seems to be an issue with the CDN.
- it is failing for US
- it is succeeding in Germany

Thanks
Martin

**Comment by JakeChampion** [comment]
Hi thanks for the report, this was an issue with the CDN provider we use and has since been resolved 👍

**Comment by msbannert** [comment]
Unfortunately, the fix didnt last very long, since about feb-27 the url https://cdn.polyfill.io/v1/polyfill.min.js is again not reachable from west europe.
