### ISSUE TITLE
The "polyfills.io" service is unavailable

### ISSUE THREAD

**Issue by Liu-huaicheng** [JakeChampion/polyfill-service#2761]
## What
_Refer to Title_

## Details
The domain "polyfills.io" was for resolving the problem of "polyfill" can not be accessed in Malaysia. Refer to:  https://github.com/JakeChampion/polyfill-service/issues/2638#issuecomment-913573567

I have checked the DNS, it can't be resolved
![image](https://github.com/JakeChampion/polyfill-service/assets/57707288/6517f6bc-2903-46dd-817e-4ed5a8148305)
Checks from [Dig Web Interface](https://www.digwebinterface.com/?hostnames=polyfills.io%0D%0Apolyfill.io&type=&useresolver=8.8.4.4&ns=all&nameservers=)

**Comment by JakeChampion** [comment]
Hi, yes, I do not own the polyfills.io domain, if it no longer resolves, that is out of my control. Is polyfill.io still blocked in Malaysia?

**Comment by pmjhonwang** [comment]
> 

u can self host

**Comment by pmjhonwang** [comment]
> ## What
> _Refer to Title_
> 
> ## Details
> The domain "polyfills.io" was for resolving the problem of "polyfill" can not be accessed in Malaysia. Refer to: [#2638 (comment)](https://github.com/JakeChampion/polyfill-service/issues/2638#issuecomment-913573567)
> 
> I have checked the DNS, it can't be resolved ![image](https://user-images.githubusercontent.com/57707288/256748533-6517f6bc-2903-46dd-817e-4ed5a8148305.png) Checks from [Dig Web Interface](https://www.digwebinterface.com/?hostnames=polyfills.io%0D%0Apolyfill.io&type=&useresolver=8.8.4.4&ns=all&nameservers=)

Self Host it!

**Comment by Liu-huaicheng** [comment]
> Hi, yes, I do not own the polyfills.io domain, if it no longer resolves, that is out of my control. Is polyfill.io still blocked in Malaysia?

Not Sure for now, we have replaced the domain with the `polyfill.io`, Keep monitoring the stability

**Comment by Liu-huaicheng** [comment]
> > Hi, yes, I do not own the polyfills.io domain, if it no longer resolves, that is out of my control. Is polyfill.io still blocked in Malaysia?
> 
> Not Sure for now, we have replaced the domain with the `polyfill.io`, Keep monitoring the stability

Looks like the stability of the `polyfill.io` domain is fine, but for safety's sake, we will create a CDN that points o the `polyfill.io` domain as a backup.
![image](https://github.com/JakeChampion/polyfill-service/assets/57707288/7375aef4-81f9-467e-af38-756f321b9c18)
