### ISSUE TITLE
CONTRIBUTING.md guide question / local service running

### ISSUE THREAD

**Issue by bobstrecansky** [JakeChampion/polyfill-service#2769]
## What

I was attempting to run a local version of this service.  Using the [CONTRIBUTING.md](https://github.com/JakeChampion/polyfill-service/blob/main/.github/CONTRIBUTING.md) did not start a server as expected.   

## Details

It appears that the Fastly CLI (using Viceroy under the covers) was added to this project relatively recently.   When I attempt to follow the getting started steps in the CONTRIBUTING.md, I get an error message about viceroy.  

```
$ git clone https://github.com/JakeChampion/polyfill-service.git
$ cd polyfill-service
$ npm ci
$ npm run build # build the assets for the website
$ npm start # start a server on 127.0.0.1:8080

> start
> viceroy bin/main.wasm -C fastly.toml

sh: viceroy: command not found
```

Just wanted to know what the preferred way to run this locally is.

**Comment by JakeChampion** [comment]
Thanks for the issue @bobstrecansky - I have now updated the command to use the fastly cli instead of assuming viceroy is installed and in the users PATH 👍

**Comment by bobstrecansky** [comment]
@JakeChampion - very much appreciate the swift response.  I've tested the version that you've updated on `main`, and I noticed two other small issues:

1.  when I run `npm ci` with the latest node version (node 20.7.0), I also need to add a `--force` flag to have the dependencies hash out as expected.

2.  When I run `npm start`, the viceroy server serves a 500 response, because it's unable to find the KVStore for what I'm assuming is the current polyfill library.
 
I've attached a full gist of the server output here:
https://gist.github.com/bobstrecansky/2ac3760b857657dc938fd9ee4378f802

Most notably here is the error about the KVStore:
https://gist.github.com/bobstrecansky/2ac3760b857657dc938fd9ee4378f802#file-gistfile1-txt-L342

**Comment by bobstrecansky** [comment]
(that `--force` may alternatively need to be a `--legacy-peer-deps`, not quite sure)

**Comment by JakeChampion** [comment]
ah oh, you first need to run `npm run build` and then run `./update-local-object-stores.sh`, after that `npm start` should work

**Comment by bobstrecansky** [comment]
I think I also need to install `https://github.com/JakeChampion/c-at-e-file-server/releases/tag/main` in order to use that `./update-local-object-stores.sh` script correctly.  Trying that out now.  If I can get this to work, I'll let you know and hopefully be able to share a Dockerfile for this.
