### ISSUE TITLE
SSL Certificate of polyfill.io is not trusted

### ISSUE THREAD

**Issue by victorr99** [JakeChampion/polyfill-service#2783]
The SSL certificate of polyfill.io is not valid anymore, this results in users (including me) not being able to access the polyfill website or the polyfill scripts.

![afbeelding](https://github.com/JakeChampion/polyfill-service/assets/23406940/6de72109-b947-4f08-9b05-e1865d0518a7)

> I guess this is not the place to report SSL certificate issues, but i couldn't find any contact information on polyfill.io

**Comment by JakeChampion** [comment]
Could you please post the fingerprint for the certificate you were seeing issues with?
Was it this one? https://crt.sh/?q=+e4d5ca402b2900956ea4e2d1023ce26e2af97f244f6e605fbbac791ca3761259

**Comment by victorr99** [comment]
Sorry for my late reaction, but i think the fingerprint is `8A:10:5D:BE:8B:11:14:4C:29:BF:1A:D4:71:4F:76:F5:28:A2:B8:EB:2B:33:AE:7E:1E:6B:E6:DC:2B:02:59:77`

A quick stackoverflow search told me to use this command:  
`openssl s_client -connect polyfill.io:443 < /dev/null 2> /dev/null | openssl x509 -fingerprint -sha256 -noout -in /dev/stdin` so i assume this is what you were asking?

**Comment by JakeChampion** [comment]
> Sorry for my late reaction, but i think the fingerprint is `8A:10:5D:BE:8B:11:14:4C:29:BF:1A:D4:71:4F:76:F5:28:A2:B8:EB:2B:33:AE:7E:1E:6B:E6:DC:2B:02:59:77`
> 
> A quick stackoverflow search told me to use this command:  
> `openssl s_client -connect polyfill.io:443 < /dev/null 2> /dev/null | openssl x509 -fingerprint -sha256 -noout -in /dev/stdin` so i assume this is what you were asking?

 I don't see that certificate as ever having existed
https://crt.sh/?q=8A105DBE8B11144C29BF1AD4714F76F528A2B8EB2B33AE7E1E6BE6DC2B025977

**Comment by JakeChampion** [comment]
I'll be closing this as I can't replicate this and no one else is reporting issues, we get 3billion+ requests a day, if there was a cert issue we would be made aware of it by many people
