### ISSUE TITLE
Issue with Webview in Android 13 Version

### ISSUE THREAD

**Issue by jhso-dev** [JakeChampion/polyfill-service#2796]
Bug report

## What
Issue with Webview in Android 13 Version for "https://cdn.polyfill.io/v2/polyfill.min.js"

I'm encountering an issue when attempting to download "https://cdn.polyfill.io/v2/polyfill.min.js" in Android 13's Webview. 
The problem manifests as a 503 error or a delay in response exceeding one minute. 
Interestingly, the issue is not present when using "https://cdn.polyfill.io/v2/polyfill.js".
<img width="703" alt="Screenshot 2023-12-16 at 10 58 18 PM" src="https://github.com/JakeChampion/polyfill-service/assets/64390727/015e114e-d73e-466a-baed-cce9c6c227ee">

## Details
User-Agent: Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

## Additional information
The alternative URL "https://cdn.polyfill.io/v2/polyfill.js" does not exhibit any problems.

**Comment by JakeChampion** [comment]
Thanks for the report, this should be fixed now 🙂
