### ISSUE TITLE
Error loading polyfill from CDN - Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by connell-theaa** [JakeChampion/polyfill-service#2835]
type: Bug

## What
When trying to load/use the polyfill library from https://cdn.polyfill.io/v3/polyfill.min.js Chrome browser shows the following error:- 

```
Uncaught TypeError: Cannot convert a Symbol value to a string
    at te (polyfill.min.js:6:22186)
```

## Details
This occurs on Chrome 121.0.6167.184 (Official Build) (x86_64)

**Comment by svicervlad** [comment]
Looks like this related https://github.com/polyfillpolyfill/polyfill-service/issues/2834

**Comment by polyfillcust** [comment]
issue solved, there is problem with cdn after migration.

**Comment by MFlyer** [comment]
This is not fixed, the same error still occurs
