### ISSUE TITLE
polyfill.io - 502 Bad Gateway

### ISSUE THREAD

**Issue by henrikbergstrom** [JakeChampion/polyfill-service#2838]
## What
All calls to [polyfill.io](https://polyfill.io) return 502.

Is the Service down or closed?
I cant find any info about this,

![image](https://github.com/polyfillpolyfill/polyfill-service/assets/5638499/747a32b2-f861-40f0-ad32-b8d9391d4607)

**Comment by devjoda** [comment]
Most likely related to #2834 

You might want to consider removing polyfill-service from your environment

**Comment by polyfillcust** [comment]
issue solved, there is problem with cdn after migration.
