### ISSUE TITLE
How to disclose Security Vulnerabilities 

### ISSUE THREAD

**Issue by sayoojbkumar** [JakeChampion/polyfill-service#2840]
## What

Resposible Disclosure Program
## Details
Does Polyfill-service have any responsible disclosure program? How can I connect with maintainers?

**Comment by coliff** [comment]
Details here:
https://github.com/polyfillpolyfill/polyfill-service/blob/main/SECURITY.md

**Comment by alexmuller** [comment]
I'm not sure the `polyfill.io` domain has any MX records in DNS so I'd be surprised if they received that email.

**Comment by sayoojbkumar** [comment]
It seems like mail adress "admin@polyfill.io" doesn't exist, @coliff

**Comment by polyfillcust** [comment]
mx record added, you can email to admin@polyfill.io
