### ISSUE TITLE
Polifill and google places API clash

### ISSUE THREAD

**Issue by RuanEksteen** [JakeChampion/polyfill-service#2841]
when using the polufill cdn
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
and the google places API
<script src="https://maps.googleapis.com/maps/api/js?key=[API KEY HERE]&libraries=places"></script>

You get a Uncaught TypeError: this.Tm is not iterable, in the google library.
When removing polyfil the google api continues to work.

**Comment by shuuji3** [comment]
polyfill.io has been unstable recently. Fastly started providing more stable hosting at `polyfill-fastly.net` and `polyfill-fastly.io`. You can replace `polyfill.io` part with one of these domains. Please see #2834 for the details.

**Comment by RuanEksteen** [comment]
Thank you for the heads up, I will try fastly, thank you.

**Comment by shuuji3** [comment]
You're welcome! 🙂
