### ISSUE TITLE
Polyfill.io returns default feature set instead of the specified feature set when version specified first

### ISSUE THREAD

**Issue by aderryfarrell** [JakeChampion/polyfill-service#2855]
Bug Report

## What

This is a serious issue for us since our users are blocked. It is an even bigger problem since the version was specified in the URL as a fix for the issues that were seen last week. A quick resolution would be greatly appreciated.

Using the polyfill.io website I specified version “3.110.1” and feature “es6” and got the following URL:
https://polyfill.io/v3/polyfill.min.js?version=3.110.1&features=es6

Last week this URL worked and provided the desired features. As of today, possibly earlier this week, the URL is not providing the "es6" feature, instead, it is providing the "default" feature.
## Details

See the above section for additional case details.

Steps to Reproduce:
1.	The easiest way to see the issue is to enter the following into a web browser:
https://polyfill.io/v3/polyfill.js?version=3.110.1&features=es6
2.	View the comment at the top that specifies the version and features requested.

Expected: The version should be “3.110.1” and the Features requested should be “es6”.

Actual: The version is correct, but the Features requested are “default”.

Environment:
Our users are accessing the service from a C# WebBrowser Element which is IE11 from Windows 10/11. I have followed the above steps with the latest Firefox and Edge Web Browsers on Windows 11.

**Comment by polyfillcust** [comment]
issue fixed.
![1](https://github.com/polyfillpolyfill/polyfill-service/assets/161748781/dfaf2726-9d13-4655-9529-d02a5164f20d)
![2](https://github.com/polyfillpolyfill/polyfill-service/assets/161748781/9e08570b-ddee-4bac-bf68-0a1e26d3f51a)
