### ISSUE TITLE
Order of query parameters matter

### ISSUE THREAD

**Issue by HJSielcken** [JakeChampion/polyfill-service#2856]
Bug Report

## What
In safari 12 (and probably also other browsers)
This gives the desired result
https://cdn.polyfill.io/v3/polyfill.js?features=ResizeObserver&flags=gated&rum=0&unknown=polyfill

However when changing the order of the query parameters to for instance
https://cdn.polyfill.io/v3/polyfill.js?flags=gated&rum=0&unknown=polyfill&features=ResizeObserver

yields
```
/*
 * Polyfill service v3.111.0
 * For detailed credits and licence information see https://polyfill.io.
 * 
 * Features requested: default
 * 
*/


/* No polyfills needed for current settings and browser */
```
I do not expect that the order of the queryparameters meter

**Comment by polyfillcust** [comment]
both url is working now.
